version: '3.7'
services:
    web:
        image: node:10.15.0-alpine
        env_file:
            - config/config.env
            - config/secrets.env
        volumes:
            - ./app:/app
        working_dir: /app
        ports:
            - 80:3000
        command: ['npm', 'start']

    db:
        image: mysql:8.0.13
        env_file:
            - config/config.env
            - config/secrets.env
        volumes:
            - ./app:/app
        ports:
            - 3306:3306
