version: '3.7'
services:
    npm:
        image: node:10.15.0
        volumes:
            - ./app:/app
        working_dir: /app
        entrypoint: npm
        command: install

    lb:
        image: node:10.15.0
        volumes:
            - ./app:/app
        working_dir: /app
        entrypoint: /app/node_modules/.bin/lb

    test:
        image: node:10.15.0-alpine
        env_file:
            - config/config.test.env
            - config/secrets.test.env
        volumes:
            - ./app:/app
        working_dir: /app
        entrypoint: npm
        command: test

    updateSchema:
        image: node:10.15.0-alpine
        env_file:
            - config/config.env
            - config/secrets.env
        volumes:
            - ./app:/app
        working_dir: /app
        entrypoint: "node -e 'require(\"./server/bin/create-tables.js\").create(\"myapi\");'"
